### Global & dlt components
[runtime]
log_level="WARNING"

### Destinations

# nothing to configure...

### Sources

## chess

[sources.chesss.extract]
max_parallel_items = 5
workers = 2  # limit the parallel execution

# the section below defines config values for "chess_dlt_config_example" source in chess/__init__.py
[sources.chess]
config_int=123
