### Sources
# google sheets example
[credentials]
project_id=""
client_email=""
private_key = ""

### Destinations
# postgres
[destination.postgres.credentials]
database = ""
password = ""
username = ""
host = ""
port = ""
connect_timeout = ""

# bigquery
[destination.bigquery.credentials]
client_email = ""
project_id = ""
private_key = ""


# redshift
destination.redshift.credentials=""