### Sources
# google sheets example
[sources.google_spreadsheet.credentials]
project_id=""
client_email=""
private_key = ""

### Destinations
# postgres
[destination.postgres.credentials]
database = ""
password = ""
username = ""
host = ""
port = ""
connect_timeout = ""

# bigquery
[destination.bigquery.credentials]
