
destination.postgres.credentials="postgres://loader:loader@localhost:5432/dlt_data"
destination.redshift.credentials="postgres://loader:set me up@3.73.90.3:5439/chat_analytics_rasa_ci"

[destination.bigquery.credentials]
client_email = "chat-analytics-loader@chat-analytics-rasa-ci.iam.gserviceaccount.com"
private_key = "set me up"
project_id = "chat-analytics-rasa-ci"