# google sheets example
[sources.google_spreadsheet.credentials]
project_id=""
client_email=""
private_key = ""

### Destinations
# postgres
[destination.postgres.credentials]
database = ""
password = ""
username = ""
host = ""
port = ""
connect_timeout = ""

# bigquery
[destination.bigquery.credentials]
client_email = "chat-analytics-loader@chat-analytics-rasa-ci.iam.gserviceaccount.com"
private_key = "set me up"
project_id = "chat-analytics-rasa-ci"
client_email = ""
project_id = ""
private_key = ""

[destination.redshift]
credentials = "postgres://loader:set me up@3.73.90.3:5439/chat_analytics_rasa_ci"


# the section below defines secrets for "chess_dlt_config_example" source in chess/__init__.py
[sources.chess_dlt_config_example]
secret_str="secret string"  # a string secret

# a dictionary/complex secret
[sources.chess_dlt_config_example.secret_dict]
secret_key="key string"
key_index=1

[sources.pipedrive]
pipedrive_api_key="set me up!"
# redshift
destination.redshift.credentials= ""

# Example database for source in sql_database/source.py
[sources.sql_database]
database_url = "postgres://my_user:my_password@localhost:5439/my_database"


